project:
  type: website

  
website:
  page-navigation: true
  title: "Good Enough Practices for Scientific Reproducibility"
  description: "Out take on how to set up a reproducible project workflow"

  repo-url: https://github.com/camilavargasp/rladies-reproducible-workflows
  repo-actions: [edit, issue]


  sidebar:
    background: "#88398a"
    logo: "images/RLadies_hex.jpeg"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/camilavargasp/rladies-reproducible-workflows
      #   text: "GitHub organization"
      # - icon: code-square
      #   href: https://posit.cloud
      #   text: "Posit Cloud"

    style: docked
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - section: "Sections"
        contents:
          - href: introduction.qmd
            text: Introduction
          - href: organization.qmd
            text: Organization
          - href: documentation.qmd
            text: Documentation
          # - href: 4-websites/index.qmd
          #   text: Websites

  page-footer:
    right: "This page is built with 💛 and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Colleen Smith + Camila Vargas Poulsen"
    background: "#D1D9E3" # Arylide Yellow

format:
  html:
    theme:
      light: [cosmo, style/quarto-style.scss]
      # dark: [cosmo, style/sta313.scss, style/dark.scss]
    linkcolor: "#58779b"
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"

execute:
  freeze: auto